### ISSUE TITLE
User Interface

### ISSUE THREAD

**Issue by Hexxal** [Hexxal/Applikaatio#1]
Android sovellukseen käyttöliittymän prototyyppi. Mielipiteitä:

Onko tässä kaikki ruudut? (2. View:n toinen nappula ei ole vielä bindattu oikeaan Viewiin, tää täytyy selvittää)

Kun saadaan käyttöliittymä-proto lyötyä lukkoon, jaetaan tehtäviä yksilöllisesti sen jälkeen ja keskitytään core-ominaisuuksiin?

Koittakaa viedä projekti Android studioon, Android studiossa yläpalkista jostain VCS-valikon alta (vaatii Git-asennuksen). Ilmotelkaa jos ei toimi.

**Comment by TurboDemo** [comment]
Täytyy tänää kattoo kun päästään tunnille tarkemmin. Määritellää kuka haluaa tehdä mitäkin.

En vielä kerenny lataamaa, mutta todennäköisesti tänää kerkeää kun pääsee tunnille.
